fix 'StopAndWaitObservable' object has no attribute 'subscription'
The problem seems to be due to difference in handling of undefined
attributes in JavaScript and Python. In Python attributes should
be defined before accessing the attributes otherwise AttributeError
will be raised. While in JavaScript the value of such an attribute
will be 'undefined'.