Update get_started.rst
-Fixed a typo for proper code markdown.
-The "Custom operator" section gives an error on Python 3.10.6 (Windows 10 64 bits):
    TypeError: Observable.subscribe() takes from 1 to 4 positional arguments but 5 were given

Apparently, the call to "source.subscribe(...)" on line 194, requires that the "scheduler" parameter be explicitly named. 

I'm a beginner with Python as a language, PyCharm as my IDE, and using RxPy, so I might be doing things wrong, but when I name the scheduler parameter, things work as expected.